### ISSUE TITLE
[bug]: key-bindings not created when using Sheldon

### ISSUE THREAD

**Issue by snaeil** [zdharma-continuum/history-search-multi-word#6]
Many zdharma-continuum plugins seem to work with [sheldon](https://github.com/rossmacarthur/sheldon) for zsh.

I love this plugin but I didn't get it to work with sheldon.

My `plugins.toml` for sheldon looks like this:

```toml
shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'

[plugins.alias-tips]
github = 'djui/alias-tips'

[plugins.conda-zsh-completion]
github = 'esc/conda-zsh-completion'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ["{{ name }}.zsh"]

[plugins.history-search-multi-word]
github = 'zdharma-continuum/history-search-multi-word'

[plugins.oh-my-zsh]
github = 'ohmyzsh/ohmyzsh'

```

Or am I missing something?

**Comment by vladdoster** [comment]
@snaeil What exactly doesn't work?

**Comment by snaeil** [comment]
I hope following context provides better insights on what could go wrong.  

## Bug description

**Expected:**

Pressing <Ctrl+R> opens the context as in this screenshot:
![2022-04-19-132825_792x214_scrot](https://user-images.githubusercontent.com/52743746/163993331-e676cf5a-2371-4573-8beb-67cfe5408830.png)

**Actual behaviour:**

Pressing <Ctrl+R> seems to do nothing.

## My environment

### Terminal

kitty

### .zshrc (not working as described above)

```zsh
export ZSH="$HOME/.sheldon/repos/github.com/ohmyzsh/ohmyzsh"
plugins=( \
    colorize \
    docker \
    docker-compose \
    git \
    git-extras \
    pip \
    ripgrep \
    rust \
    sudo \
    # vi-mode \
    wd \
)

eval "$(sheldon source)"

``` 

### sheldon config (`plugins.toml`)

```toml
shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'

[plugins.alias-tips]
github = 'djui/alias-tips'

[plugins.conda-zsh-completion]
github = 'esc/conda-zsh-completion'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ["{{ name }}.zsh"]

[plugins.history-search-multi-word]
github = 'zdharma-continuum/history-search-multi-word'

[plugins.oh-my-zsh]
github = 'ohmyzsh/ohmyzsh'

```

**Comment by vladdoster** [comment]
@snaeil Did you figure this out?

I'm unfamiliar with sheldon, but have you read [this](https://github.com/zdharma-continuum/history-search-multi-word/blob/main/history-search-multi-word#L4)?

**Comment by snaeil** [comment]
Thank you for the hint!
Adding following ([from your link](https://github.com/zdharma-continuum/history-search-multi-word/blob/main/history-search-multi-word#L4)) to my `.zshrc` actually made it work for me:

```zsh
autoload history-search-multi-word
zle -N history-search-multi-word
zle -N history-search-multi-word-backwards history-search-multi-word
zle -N history-search-multi-word-pbackwards history-search-multi-word
zle -N history-search-multi-word-pforwards history-search-multi-word
bindkey "^R" history-search-multi-word
zstyle ":history-search-multi-word" page-size "8"
zstyle ":history-search-multi-word" highlight-color "fg=yellow,bold"
zstyle ":plugin:history-search-multi-word" synhl "yes"
zstyle ":plugin:history-search-multi-word" clear-on-cancel "no"
```

I couldn't make it work within sheldon unfortunately with something like this:
```toml
[plugins.history-search-multi-word]
github = 'zdharma-continuum/history-search-multi-word'

[plugins.history-search-multi-word-LOADER]
inline = 'autoload history-search-multi-word & zle -N history-search-multi-word & zle -N history-search-multi-word-backwards history-search-multi-word & zle -N history-search-multi-word-pbackwards history-search-multi-word & zle -N history-search-multi-word-pforwards history-search-multi-word & bindkey "^R" history-search-multi-word & zstyle ":history-search-multi-word" page-size "8" & zstyle ":history-search-multi-word" highlight-color "fg=yellow,bold" & zstyle ":plugin:history-search-multi-word" synhl "yes" & zstyle ":plugin:history-search-multi-word" clear-on-cancel "no"'
```

But I guess this is more a sheldon problem than a problem of this plugin?
